### ISSUE TITLE
Eclipse crash on startup

### ISSUE THREAD

**Issue by rodtell** [flathub/org.eclipse.Java#104] opened 2024-12-04 14:00 UTC
Latest update is crashing.
```
CompileCommand: exclude org/eclipse/jdt/internal/core/dom/rewrite/ASTRewriteAnalyzer.getExtendedRange bool exclude = true

(java:21): GdkPixbuf-CRITICAL **: 10:55:54.496: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(java:21): GdkPixbuf-CRITICAL **: 10:55:54.496: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(java:21): GdkPixbuf-CRITICAL **: 10:55:54.496: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(java:21): GdkPixbuf-CRITICAL **: 10:55:54.496: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(java:21): Gtk-CRITICAL **: 10:55:54.496: gtk_window_resize: assertion 'width > 0' failed
```
It also generates a log file, but it is over 2000 lines long, I don't know if I should add it here on description. If so, I can add it later.
Fedora 41, GNOME 47.
![Captura de tela de 2024-12-04 10-41-38](https://github.com/user-attachments/assets/68d48f3b-e109-4196-b921-161418d62f86)

**Comment by Mailaender** [comment] 2024-12-04 14:31
Not reproducible on @ArchLinux. The log excerpts you provided are not enough to diagnose this.

**Comment by rodtell** [comment] 2024-12-04 14:39
[1733322782089.log](https://github.com/user-attachments/files/18009819/1733322782089.log)
I was not able to copy and paste due to the size of it, about 2900 lines on log file.

**Comment by Mailaender** [comment] 2024-12-04 21:20
> java.lang.IllegalStateException: The System Bundle was updated. The framework must be restarted to finalize the configuration change

Sounds like you tried to install plugins and it crashed, see https://github.com/flathub/org.eclipse.Java/issues/100.

**Comment by rodtell** [comment] 2024-12-05 12:29
I do need some plugins for Eclipse, but although is not the solution; I uninstalled Eclipse, and removed the flatpak directory related to Eclipse.
```
~/.var/app/org.eclipse.Java/ 
```
Once installed, I added a JavaEE plugin that I need, and so far is working fine. 

When I removed the .eclipse directory, it did not work out for me, even without any plugins. 

It did not affect me too much (reinstalling from scratch), since all my work is in the eclipse-workspace folder, and Eclipse recognized without any issues.

**Comment by Mailaender** [comment] 2024-12-05 12:37
So you think it was update related? https://github.com/flathub/org.eclipse.Java/issues/12 is another unresolved problem.

**Comment by rodtell** [comment] 2024-12-05 12:50
> So you think it was update related? #12 is another unresolved problem.

I think so, the same kind of error and probably the log generated would gave the same info as mine. But it is not a recurring error, the update before this one worked without any issues. 

Is the splash screen startup working well for you? I just get a small blank square on top right of my screen. A minor issue that does not affect me at all, but I wonder if it is another Wayland problem with Eclipse, and not the flatpak.

**Comment by Mailaender** [comment] 2024-12-05 13:49
See https://fedoraproject.org/wiki/Eclipse#No_Splashscreen_Image as it is a Fedora related problem.

**Comment by munje** [comment] 2024-12-06 10:34
> Is the splash screen startup working well for you? I just get a small blank square on top right of my screen. A minor issue that does not affect me at all, but I wonder if it is another Wayland problem with Eclipse, and not the flatpak.

This also bugs me. I have the same behavior on my system, instead of regular splash screen I just get blank square and after it eclipse start normally. I tried clean reinstall (removed the flat dirs related to eclipse) but it is the same.
I'm using Fedora 41, Gnome 47

> See https://fedoraproject.org/wiki/Eclipse#No_Splashscreen_Image as it is a Fedora related problem.
Did anyone make a use of it? Do we have to do something after installing this package (gdk-pixbuf2-modules-extra)? 
I tried to install it but it is the same - no  splash screen and only small blank square is shown

**Comment by Mailaender** [comment] 2024-12-06 10:40
Maybe I confused it because I was testing with a tarball instead of the Flatpak installation.

**Comment by akurtakov** [comment] 2024-12-06 10:58
It should be possible to include the extra modules in the flatpak

**Comment by Mailaender** [comment] 2024-12-06 11:15
Closing this derailed discussion in favor of https://github.com/flathub/org.eclipse.Java/issues/105 and the other crash reports.

**Closed by Mailaender** 2024-12-06 11:15 UTC
Labels: bug

**Comment by ugale-deepak3010** [comment] 2025-01-09 16:19
@Mailaender  I am also using flatpak eclipse in Fedora.
Are you using Lombok? I am not able to use. struggling since last two year. 
Please could you help me if you ever used?

**Comment by Mailaender** [comment] 2025-01-09 16:35
See https://github.com/flathub/org.eclipse.Java/issues/67

**Comment by anyuruf** [comment] 2025-01-19 10:42
From https://github.com/flathub/org.eclipse.Java/issues/67
I had the same issue but looks like on Fedora, Eclipse will search for /home/iyit/.var/app/org.eclipse.Java/eclipse/plugins. Where iyit = username as mentioned earlier. So I created a folder/directory there with ```mkdir org.projectlombok.agent_1.18.36 ```  command and copied my downloaded lombok jar to the folder and the like a charm it worked.
 
@rodtell @Mailaender I feel your pain gone
